[package]
name = "xtask"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.86"
argh = "0.1.12"
bindgen = "0.70.1"
camino = "1.1.9"
cargo_metadata = "0.18.1"
