[package]
name = "nd-jpegli-sys"
version = "0.0.0"
edition = "2021"
build = "build.rs"

[dev-dependencies]
image = { version = "0.25.1", features = [ "jpeg" ], default-features = false }

[build-dependencies]
cc = "1.0.101"
cmake = "0.1.50"
